### ISSUE TITLE
Backwards compatibility with Java 8

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/speed-bagit#1]
Right now the build is failing on Java 8. Is this something that we want to support?

**Comment by mbjones** [comment]
Let's start with the same Java versions that Metacat supports, as that is the current driving application for the library.

**Comment by csjx** [comment]
I see that the POM file is targeting Java 7 for source and target code compilation, so let's bump that to Java 8 minimally.

**Comment by ThomasThelen** [comment]
Fixed in 171fdde
