### ISSUE TITLE
Add badges for travis and codecov

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/speed-bagit#2]
The current travis badge is pointing an incorrect repository; this should be pointing to the dataoneorg's travis build. The travis file is also setup to run codecov at the end of the pipeline. We should add a badge that shows the current code coverage statistics.

**Comment by mbjones** [comment]
https://travis-ci.com/github/DataONEorg/speed-bagit

**Comment by ThomasThelen** [comment]
It turns out that codecov doesn't support Travis + Maven + Java 11 and above. See [this](https://github.com/cobertura/cobertura/issues/381) and linked issues. Travis CI has been hooked up and it doesn't look like the codecov plugin is actively maintained. Closing this issue.
