### ISSUE TITLE
Failure on Duplicate Filenames

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/speed-bagit#23]
When streaming a bag with two matching filenames, the system seems to lock up. This is because the error is occurring in the spawned [thread](https://github.com/DataONEorg/speed-bagit/blob/main/src/main/java/org/dataone/speedbagit/SpeedBagIt.java#L289) that writes the data to the output stream. There _should_ be a way for us to catch this exception and exit.

**Comment by ThomasThelen** [comment]
Here's the unit test that _should_ pass when this is fixed

```
    @Test
    public void testDataBagExportDuplicateFilename() {
        double bagVersion = 1.0;
        String checksumAlgorithm = "MD5";
        Map<String, String> bagMetadata = new HashMap<>();

        SpeedBagIt bag ;
        Path bagFilePath;
        try {
            bag = new SpeedBagIt(bagVersion, checksumAlgorithm, bagMetadata);

            String dataFile1 = "1234, 9876, 3845";
            String dataFile2 = "1234, 9876, 38";

            // Simulate getting a stream to those bytes and adding them to the bag
            InputStream dataFileStream1 = new ByteArrayInputStream(dataFile1.getBytes(StandardCharsets.UTF_8));
            InputStream dataFileStream2 = new ByteArrayInputStream(dataFile2.getBytes(StandardCharsets.UTF_8));
            bag.addFile(dataFileStream1, "data/data_file1.csv", MessageDigest.getInstance("MD5"), false);
            bag.addFile(dataFileStream2, "data/data_file1.csv", MessageDigest.getInstance("MD5"), false);

            Path bagPath = Paths.get(directory.toString() + "dataBag.zip");
            bagFilePath = Files.createFile(bagPath);
            FileOutputStream fos = new FileOutputStream(bagFilePath.toString());
            InputStream bagStream = bag.stream();
            IOUtils.copy(bagStream, fos);

            // Open to bag to read
            ZipFile zipFile = new ZipFile(bagFilePath.toString());
            // Make sure that the bag files are correct
            this.validateBagItFiles(zipFile, bagVersion, bag.getPayloadFileCount());
            Files.delete(bagFilePath);

        } catch (IOException e) {
            return;
        } catch (NoSuchAlgorithmException e) {
            fail(e);
        }
        fail("java.util.zip.ZipException should have thrown");
    }
```

**Comment by ThomasThelen** [comment]
We should expand [this](https://github.com/DataONEorg/speed-bagit/blob/22d8d5132450a3883a60fa179e8d2ac78cd54671/src/main/java/org/dataone/speedbagit/SpeedBagIt.java#L262) exception clause out so that we tell the calling method the specific problem. It should get trickled up to Metacat which would most likely throw some type of ServiceException.

**Comment by taojing2002** [comment]
The exception looks like:
```
java.util.zip.ZipException: duplicate entry: data/CO1_300234068118580_2020P226.csv
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
	at org.dataone.speedbagit.SpeedBagIt.streamFile(SpeedBagIt.java:265)
	at org.dataone.speedbagit.SpeedBagIt.access$200(SpeedBagIt.java:61)
	at org.dataone.speedbagit.SpeedBagIt$1.run(SpeedBagIt.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ThomasThelen** [comment]
How were you able to get the exception? My understanding is that you can't catch exceptions in code inside a Runnable (which we use) from the outer scope (eg we can't try/catch [this](https://github.com/DataONEorg/speed-bagit/blob/main/src/main/java/org/dataone/speedbagit/SpeedBagIt.java#L289) function). I think the solution here is to transform the runnable into a Callable

**Comment by taojing2002** [comment]
@ThomasThelen I just spotted it on the tomcat log file when we were trying to download a problematic package.

**Comment by ThomasThelen** [comment]
Interesting... I'll take a look at this, this weekend. I think Metacat should be checking for file path collisions before sending the files to SpeedBagIt (oops I should have done this). Otherwise you'll be catching an exception from here-which would be too late since the bag would be partially served when the exception throws.

**Comment by mbjones** [comment]
Given that these name duplication issues are likely unavoidable, one way to make speed-bagit more robust would be to catch these naming exceptions and deal with them during serialization. I can see a couple of paths forward:

1) skip the second file and put an error note in somehow to the bag that the file was skipped because of the conflict
2) add the file with the duplicate name with a postfix random string or something to make it unique; again, put an error file that indicates there was a naming conflict. 

Either of these would allow the bagit to be generated even in the face of naming errors. We;d have to restructure the loop through the files so the errors could be caught without breaking out of the loop, but should be straightforward.

**Comment by ThomasThelen** [comment]
^^ That solution totally works.

Another possible route is throwing on [addFile](https://github.com/DataONEorg/speed-bagit/blob/main/src/main/java/org/dataone/speedbagit/SpeedBagIt.java#L162) if a file with the same path exists. If thrown, Metacat picks a new filename, records some metadata about the matching filenames, and then adds the file with a new path. That way Metacat knows about the duplicate file and can do whatever it needs to do (like create a new file, append the Readme, etc).

At the least, I think we're fairly set on turning the Runnable into a Callable, for best practices in general (we really don't want the thread hanging the way I see it in the unit test).

**Comment by mbjones** [comment]
See issue #27 and PR #28
