### ISSUE TITLE
Check for name collisions on addFile

### ISSUE THREAD

**Issue by ThomasThelen** [DataONEorg/speed-bagit#27]
Branching from #23 - it would be nice to get an early warning that there's a name collision. When two files (data or tag) are added to a bag and their paths match-throw an exception.

**Comment by mbjones** [comment]
I noticed there is a related issue to this in Metacat, which would likely be fixed via this change in bagit: https://github.com/NCEAS/metacat/issues/1443

**Comment by mbjones** [comment]
Merged fixes from @ThomasThelen -- so now an exception is thrown when filenames are duplicated. This passes the responsibility for dealing with the duplication to the client calling the library. For example, when Metacat is creating a bagit file, an exception on `addFile` will need to be addressed, either by aborting the request altogether and sending back an appropriate error, or by modifying the filename and adding it to the bag (possibly with some sort of an error indication in the bag). See also issue #23
